theme: jekyll-theme-minimal
title: An standalone CSS optimizer in PHP
description: Optimize your CSS file with PHP
logo: /assets/img/logo.png
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
