theme: jekyll-theme-minimal
title: CSSLoL - An standalone CSS optimizer in PHP. 
description: CSSLoL, optimize your CSS file in PHP.
logo: /assets/img/logo.png
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
